-- MySQL Script generated by MySQL Workbench
-- jeu. 04 févr. 2021 07:45:35 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plants
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plants` ;

-- -----------------------------------------------------
-- Schema plants
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plants` DEFAULT CHARACTER SET utf8 ;
USE `plants` ;

-- -----------------------------------------------------
-- Table `plants`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plants`.`categories` ;

CREATE TABLE IF NOT EXISTS `plants`.`categories` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plants`.`plantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plants`.`plantes` ;

CREATE TABLE IF NOT EXISTS `plants`.`plantes` (
  `idPlante` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idPlante`),
  INDEX `fk_Plante_Categorie_idx` (`Categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Plante_Categorie`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `plants`.`categories` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plants`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plants`.`products` ;

CREATE TABLE IF NOT EXISTS `plants`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `price` INT NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `Plante_idPlante` INT NOT NULL,
  PRIMARY KEY (`idproducts`),
  INDEX `fk_products_Plante1_idx` (`Plante_idPlante` ASC) VISIBLE,
  CONSTRAINT `fk_products_Plante1`
    FOREIGN KEY (`Plante_idPlante`)
    REFERENCES `plants`.`plantes` (`idPlante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
